### ISSUE TITLE
What is the relationship of this repo to the other swotsimulator?

### ISSUE THREAD

**Issue by ezaron** [SWOTsimulator/swotsimulator#30]
Hi Jinbo, Lucile:
Which swotsimulator project has the up-to-date noise models and orbit ephemeris? This one, or the other one:
https://github.com/CNES/swot_simulator
-Ed

**Comment by jinbow** [comment]
Hi Ed, 

  The two versions should have the same error model based on Esteban-Fernandez et al., 2014 and use the same orbit ephemeris. However, the swaths are different between the two. 

Jinbo

**Comment by ezaron** [comment]
-- thanks, Jinbo. I posted the same question over on the other project, and Frederic Briol replied, stating that that project is more up-to-date.

**Comment by jinbow** [comment]
Hi Ed, 

 As far as I know, there are only one error specification based on Dani's document and one set of orbits (fast and 21d repeat) since 2015. Software can be different but those parameters should be consistent. I read the conversations over the other site, and think that Frederic's 'up-to-date' meant it was written recently and used to generate the official mission sample data. It was my understanding too. 

Jinbo

**Comment by ezaron** [comment]
Jinbo,
I am working with a programmer who used this version of the simulator, and she used the swot014_fastsampling.txt file. I noticed that the crossovers did not seem to match the .kml distributed at the AVISO site. We also noticed the projects have different files under the data/ directory.
-Ed

**Comment by jinbow** [comment]
Hi Ed,  

The correct orbits should be ephem_calval_june2015_ell.txt ephem_science_sept2015_ell.txt in the data folder, which are consistent with AVISO site. 

I only aware of these two files in this folder. What other data directories exit there? I can help take a look. 

Jinbo

**Comment by ezaron** [comment]
Take a look:
https://github.com/SWOTsimulator/swotsimulator/tree/master/data
-- maybe some files are deprecated.

**Comment by lgaultier** [comment]
Hi Ed, 
The noise has actually evolved in the CNES version of the simulator ( better randomness, simulation of roll-phase cross over correction, swh varying in time and space). This version could be quite difficult to use depending on what you want to do though. 
I am planning to update the error budget as some people do not wish to switch to the CNES version, let me know if it is your case so that I can make it a priority in my todolist.
Lucile

**Comment by ezaron** [comment]
Thanks, Lucile. I have not used the SWOTsimulator code in over a year, and a colleague recently tried to use it to simulate data along the Cal/Val swaths. We noticed that the swath locations did not match the .kml available at the AVISO site, and then we noticed that there are two separate github projects. Perhaps we used it incorrectly, but it seems that the other github project contains a deprecated swath location file.
We want to use the version with the most realistic simulations based on our current understanding of the noise budget.

**Comment by jinbow** [comment]
thanks Ed. It is in plain sight ... Pre2015 files are deprecated. We should remove those historical files.

**Comment by lgaultier** [comment]
Hi Ed, 
Then you should use the CNES version, it is a bit more tricky to install and use, let me know if you want to schedule a quick chat to discuss how to use the new version. Basically you have to write a plugin to read your own model data and feed the interpolator. 
You can contact me by email to schedule a zoom if you need.

**Comment by ezaron** [comment]
-- thx. I am working with a programmer on this and she will contact you if we get stuck.
